version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: order_test_nginx
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ./application:/var/www/application
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - application

  php:
    container_name: order_test_php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./application:/var/www/application
      - ./migrations:/var/www/migrations
      - ./sql:/var/www/sql_dump
    environment:
      APP_ENV: '${ENV}'
      DB_HOST: '${DB_HOST}'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - db
    networks:
      - application

  db:
    image: mysql:8.0
    container_name: order_test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - application

networks:
  application:
    driver: bridge
